-- An invitation is accepted by the database, for the address it was sent to
-- (ADR 0003, amending ADR 0002).
--
-- 0009 let the invitation lane write its own way in: an insert into
-- `workspace_members` with whatever role the request named, and — meant but
-- never reachable — an update of the invitation it presented. The update was
-- refused by the invitation's own `WITH CHECK`, so no invitation could be
-- accepted once the barrier went on; and widening that check would have let the
-- lane rewrite any column of the row, `role` included. So the lane loses its
-- writes, and joining becomes one function that decides and writes together.

-- The whole acceptance, as the owner.
--
-- It reads the lane's two settings — the token's hash and the person presenting
-- it — and refuses, as a value the page has words for, anything that is not a
-- live invitation sent to that person's verified address. Otherwise it claims
-- the invitation and writes the membership with the role the invitation
-- carries, never one the request supplies. `FOR UPDATE` is what makes the claim
-- single: a second acceptance racing this one waits for the lock, re-reads the
-- row as accepted and is told it does not exist.
--
-- The membership id is a parameter because ids are generated by the
-- application (§4.1), not by whichever Postgres a managed host is running.
--
-- SECURITY DEFINER because nothing the application role may do can write a
-- membership into a workspace it is not already in — which is the point. So
-- `search_path` is pinned with `pg_temp` last, every relation is qualified, and
-- EXECUTE belongs to `planora_app` alone.
CREATE OR REPLACE FUNCTION app.accept_invitation(membership_id uuid)
  RETURNS TABLE (outcome text, joined_workspace uuid, joined_as text)
  LANGUAGE plpgsql
  VOLATILE
  SECURITY DEFINER
  SET search_path = pg_catalog, pg_temp
AS $$
DECLARE
  invitation public.workspace_invitations%ROWTYPE;
  person public.users%ROWTYPE;
  presenting uuid := app.current_user_id();
BEGIN
  IF presenting IS NULL THEN
    RAISE EXCEPTION 'accepting an invitation needs a person: planora.user_id is not set';
  END IF;

  SELECT i.* INTO invitation
  FROM public.workspace_invitations i
  WHERE i.token_hash = app.current_invitation()
  FOR UPDATE;

  -- Unknown, already spent, or one that grants ownership, which no invitation
  -- may: they all read the same from outside.
  IF NOT FOUND OR invitation.accepted_at IS NOT NULL OR invitation.role = 'owner' THEN
    RETURN QUERY SELECT 'invalid-token'::text, NULL::uuid, NULL::text;
    RETURN;
  END IF;

  IF invitation.expires_at <= now() THEN
    RETURN QUERY SELECT 'expired'::text, NULL::uuid, NULL::text;
    RETURN;
  END IF;

  SELECT u.* INTO person FROM public.users u WHERE u.id = presenting;

  IF NOT FOUND
    OR NOT person.email_verified
    OR lower(person.email) <> lower(invitation.email) THEN
    RETURN QUERY SELECT 'wrong-account'::text, NULL::uuid, NULL::text;
    RETURN;
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.workspace_members m
    WHERE m.workspace_id = invitation.workspace_id AND m.user_id = presenting
  ) THEN
    RETURN QUERY SELECT 'already-member'::text, invitation.workspace_id, NULL::text;
    RETURN;
  END IF;

  UPDATE public.workspace_invitations i
  SET accepted_at = now()
  WHERE i.id = invitation.id;

  INSERT INTO public.workspace_members (id, workspace_id, user_id, role)
  VALUES (membership_id, invitation.workspace_id, presenting, invitation.role);

  RETURN QUERY SELECT 'joined'::text, invitation.workspace_id, invitation.role;
END
$$;
--> statement-breakpoint

REVOKE ALL ON FUNCTION app.accept_invitation(uuid) FROM PUBLIC;
--> statement-breakpoint

GRANT EXECUTE ON FUNCTION app.accept_invitation(uuid) TO planora_app;
--> statement-breakpoint

-- A membership is written into the workspace the request is already in, and
-- nowhere else. The invitation branch that stood here is the function above.
ALTER POLICY workspace_members_tenant ON public.workspace_members
  WITH CHECK (workspace_id = app.current_workspace());
--> statement-breakpoint

-- The invitation lane reads its invitation — the page says "expired" and
-- "already used" — and writes nothing. The workspace's own lane keeps every
-- command, bound to the workspace as before.
DROP POLICY workspace_invitations_tenant ON public.workspace_invitations;
--> statement-breakpoint

CREATE POLICY workspace_invitations_tenant ON public.workspace_invitations
  USING (workspace_id = app.current_workspace())
  WITH CHECK (workspace_id = app.current_workspace());
--> statement-breakpoint

CREATE POLICY workspace_invitations_presented ON public.workspace_invitations
  FOR SELECT
  USING (token_hash = app.current_invitation());
